/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ernes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private char jugadorActual = 'X';
    private int[][] matrizJuego = new int[3][3];
    private boolean juegoFinalizado = false;
    private int juegosGanadosX = 0;
    private int juegosGanadosY = 0;
    private int contadorTurnos = 0;

    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnValor1 = new javax.swing.JLabel();
        btnValor2 = new javax.swing.JLabel();
        btnValor3 = new javax.swing.JLabel();
        btnValor4 = new javax.swing.JLabel();
        btnValor5 = new javax.swing.JLabel();
        btnValor6 = new javax.swing.JLabel();
        btnValor7 = new javax.swing.JLabel();
        btnValor8 = new javax.swing.JLabel();
        btnValor9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtJugadorActual = new javax.swing.JLabel();
        btnReiniciar = new javax.swing.JLabel();
        txtResultados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe");
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(500, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 600));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 500));

        btnValor1.setBackground(new java.awt.Color(0, 153, 153));
        btnValor1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnValor1.setForeground(new java.awt.Color(255, 255, 255));
        btnValor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnValor1.setText("-");
        btnValor1.setToolTipText("");
        btnValor1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValor1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnValor1.setName("0,0"); // NOI18N
        btnValor1.setOpaque(true);
        btnValor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnValor1MousePressed(evt);
            }
        });

        btnValor2.setBackground(new java.awt.Color(0, 153, 153));
        btnValor2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnValor2.setForeground(new java.awt.Color(255, 255, 255));
        btnValor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnValor2.setText("-");
        btnValor2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValor2.setName("0,1"); // NOI18N
        btnValor2.setOpaque(true);
        btnValor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnValor1MousePressed(evt);
            }
        });

        btnValor3.setBackground(new java.awt.Color(0, 153, 153));
        btnValor3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnValor3.setForeground(new java.awt.Color(255, 255, 255));
        btnValor3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnValor3.setText("-");
        btnValor3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValor3.setName("0,2"); // NOI18N
        btnValor3.setOpaque(true);
        btnValor3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnValor1MousePressed(evt);
            }
        });

        btnValor4.setBackground(new java.awt.Color(0, 153, 153));
        btnValor4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnValor4.setForeground(new java.awt.Color(255, 255, 255));
        btnValor4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnValor4.setText("-");
        btnValor4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValor4.setName("1,0"); // NOI18N
        btnValor4.setOpaque(true);
        btnValor4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnValor1MousePressed(evt);
            }
        });

        btnValor5.setBackground(new java.awt.Color(0, 153, 153));
        btnValor5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnValor5.setForeground(new java.awt.Color(255, 255, 255));
        btnValor5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnValor5.setText("-");
        btnValor5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValor5.setName("1,1"); // NOI18N
        btnValor5.setOpaque(true);
        btnValor5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnValor1MousePressed(evt);
            }
        });

        btnValor6.setBackground(new java.awt.Color(0, 153, 153));
        btnValor6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnValor6.setForeground(new java.awt.Color(255, 255, 255));
        btnValor6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnValor6.setText("-");
        btnValor6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValor6.setName("1,2"); // NOI18N
        btnValor6.setOpaque(true);
        btnValor6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnValor1MousePressed(evt);
            }
        });

        btnValor7.setBackground(new java.awt.Color(0, 153, 153));
        btnValor7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnValor7.setForeground(new java.awt.Color(255, 255, 255));
        btnValor7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnValor7.setText("-");
        btnValor7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValor7.setName("2,0"); // NOI18N
        btnValor7.setOpaque(true);
        btnValor7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnValor1MousePressed(evt);
            }
        });

        btnValor8.setBackground(new java.awt.Color(0, 153, 153));
        btnValor8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnValor8.setForeground(new java.awt.Color(255, 255, 255));
        btnValor8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnValor8.setText("-");
        btnValor8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValor8.setName("2,1"); // NOI18N
        btnValor8.setOpaque(true);
        btnValor8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnValor1MousePressed(evt);
            }
        });

        btnValor9.setBackground(new java.awt.Color(0, 153, 153));
        btnValor9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        btnValor9.setForeground(new java.awt.Color(255, 255, 255));
        btnValor9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnValor9.setText("-");
        btnValor9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnValor9.setName("2,2"); // NOI18N
        btnValor9.setOpaque(true);
        btnValor9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnValor1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnValor4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnValor5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnValor7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(btnValor8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValor9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValor6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValor3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValor1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValor2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValor3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValor4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValor6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValor5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnValor7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValor9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnValor8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Player:");

        txtJugadorActual.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtJugadorActual.setText("X");

        btnReiniciar.setBackground(new java.awt.Color(0, 153, 153));
        btnReiniciar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnReiniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnReiniciar.setText("Reset");
        btnReiniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReiniciar.setOpaque(true);
        btnReiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnReiniciarMousePressed(evt);
            }
        });

        txtResultados.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtResultados.setText("X: 0 | O: 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtResultados)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJugadorActual)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtJugadorActual)
                    .addComponent(txtResultados)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnValor1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValor1MousePressed
        // TODO add your handling code here:
        JLabel botonApuntador = (JLabel) evt.getComponent();
        if (botonApuntador.getText().equals("-") && !juegoFinalizado) {
            contadorTurnos++;
            botonApuntador.setText(jugadorActual + "");
            boolean resultado = jugadorGano(
                    Integer.parseInt(botonApuntador.getName().charAt(0) + ""),
                    Integer.parseInt(botonApuntador.getName().charAt(2) + ""));
            if (resultado) {
                JOptionPane.showMessageDialog(null, "Gano el Jugador " + jugadorActual);
                juegoFinalizado = true;
                this.setTitle("Tic Tac Toe | Win player: " + jugadorActual);
                if (jugadorActual == 'X') {
                    juegosGanadosX++;
                } else {
                    juegosGanadosY++;
                }
                txtResultados.setText("X: " + juegosGanadosX + " | O: " + juegosGanadosY);
            } else {
                if (contadorTurnos == 9) {
                    JOptionPane.showMessageDialog(null, "Juego terminado en empate");
                }
                jugadorActual = jugadorActual == 'X' ? 'O' : 'X';
                txtJugadorActual.setText(jugadorActual + "");
            }
        }
    }//GEN-LAST:event_btnValor1MousePressed

    private boolean jugadorGano(int x, int y) {
        matrizJuego[y][x] = jugadorActual == 'X' ? 1 : 4;
        int resultadoGanador = jugadorActual == 'X' ? 3 : 12;
        int total = matrizJuego[0][0] + matrizJuego[0][1] + matrizJuego[0][2];
        if (total == resultadoGanador) {
            pintarBotones(btnValor1, btnValor4, btnValor7, Color.green);
            return true;
        }
        total = matrizJuego[1][0] + matrizJuego[1][1] + matrizJuego[1][2];
        if (total == resultadoGanador) {
            pintarBotones(btnValor2, btnValor5, btnValor8, Color.green);
            return true;
        }
        total = matrizJuego[2][0] + matrizJuego[2][1] + matrizJuego[2][2];
        if (total == resultadoGanador) {
            pintarBotones(btnValor3, btnValor6, btnValor9, Color.green);
            return true;
        }
        total = matrizJuego[0][0] + matrizJuego[1][0] + matrizJuego[2][0];
        if (total == resultadoGanador) {
            pintarBotones(btnValor1, btnValor2, btnValor3, Color.green);
            return true;
        }
        total = matrizJuego[0][1] + matrizJuego[1][1] + matrizJuego[2][1];
        if (total == resultadoGanador) {
            pintarBotones(btnValor4, btnValor5, btnValor6, Color.green);
            return true;
        }
        total = matrizJuego[0][2] + matrizJuego[1][2] + matrizJuego[2][2];
        if (total == resultadoGanador) {
            pintarBotones(btnValor7, btnValor8, btnValor9, Color.green);
            return true;
        }
        total = matrizJuego[0][0] + matrizJuego[1][1] + matrizJuego[2][2];
        if (total == resultadoGanador) {
            pintarBotones(btnValor1, btnValor5, btnValor9, Color.green);
            return true;
        }
        total = matrizJuego[0][2] + matrizJuego[1][1] + matrizJuego[2][0];
        if (total == resultadoGanador) {
            pintarBotones(btnValor3, btnValor5, btnValor7, Color.green);
            return true;
        }
        return false;
    }

    private void pintarBotones(JLabel boton1, JLabel boton2, JLabel boton3, Color color) {
        boton1.setBackground(color);
        boton2.setBackground(color);
        boton3.setBackground(color);
    }

    private void btnReiniciarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReiniciarMousePressed
        // TODO add your handling code here:
        btnValor1.setText("-");
        btnValor2.setText("-");
        btnValor3.setText("-");
        pintarBotones(btnValor1, btnValor2, btnValor3, new Color(0, 153, 153));
        btnValor4.setText("-");
        btnValor5.setText("-");
        btnValor6.setText("-");
        pintarBotones(btnValor4, btnValor5, btnValor6, new Color(0, 153, 153));
        btnValor7.setText("-");
        btnValor8.setText("-");
        btnValor9.setText("-");
        pintarBotones(btnValor7, btnValor8, btnValor9, new Color(0, 153, 153));
        txtJugadorActual.setText("X");
        jugadorActual = 'X';
        this.setTitle("Tic Tac Toe");
        contadorTurnos = 0;
        juegoFinalizado = false;
        for (int indiceX = 0; indiceX < 3; indiceX++) {
            for (int indiceY = 0; indiceY < 3; indiceY++) {
                matrizJuego[indiceX][indiceY] = 0;
            }
        }
    }//GEN-LAST:event_btnReiniciarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnReiniciar;
    private javax.swing.JLabel btnValor1;
    private javax.swing.JLabel btnValor2;
    private javax.swing.JLabel btnValor3;
    private javax.swing.JLabel btnValor4;
    private javax.swing.JLabel btnValor5;
    private javax.swing.JLabel btnValor6;
    private javax.swing.JLabel btnValor7;
    private javax.swing.JLabel btnValor8;
    private javax.swing.JLabel btnValor9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtJugadorActual;
    private javax.swing.JLabel txtResultados;
    // End of variables declaration//GEN-END:variables
}
